<?php

namespace CharitySwimRun\classes\model;

use Doctrine\ORM\Mapping as ORM;
use Doctrine\DBAL\Types\Types;

#[ORM\Entity]
#[ORM\Table(name: 'femalefirstnames', options: ['charset' => 'utf8mb4', 'collate' => 'utf8mb4_unicode_ci'])]
class EA_FemaleFirstname
{


    #[ORM\Column(type: Types::INTEGER, name: "uid")]
    #[ORM\GeneratedValue]
    #[ORM\Id]
    private ?int $id = null;

    #[ORM\Column(type: Types::STRING, name: "firstname")]
    private string $firstname = "";



    /**
     * Initialize a new female firstname entity.
     */
    public function __construct(?int $id = null, string $firstname = "")
    {
        $this->id = $id;
        $this->firstname = $firstname;
    }

    /**
     * Get the identifier of the entity.
     */
    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * Set the identifier of the entity.
     */
    public function setId(?int $id)
    {
        $this->id = $id;
    }

    /**
     * Get the firstname.
     */
    public function getFirstname(): string
    {
        return $this->firstname;
    }

    /**
     * Set the firstname.
     */
    public function setFirstname(string $firstname): void
    {
        $this->firstname = $firstname;
    }

    /**
     * Get an array of standard female firstnames.
     */
    public static function getStandardElemente(): array
    {
        $names = [
            'Alexandra',
            'Alia',
            'Alida',
            'Alina',
            'Alisa',
            'Alma',
            'Alicia',
            'Amalia',
            'Amelie',
            'Anastasia',
            'Andrea',
            'Angela',
            'Angelika',
            'Angelina',
            'Anika',
            'Anita',
            'Anja',
            'Anke',
            'Ann-Kathrin',
            'Annabell',
            'Annette',
            'Annemarie',
            'Annett',
            'Annika',
            'Anthea',
            'Antje',
            'Antonia',
            'Antonia Luise',
            'Ariane',
            'Astrid',
            'Aurelia',
            'Aylin',
            'Bärbel',
            'Barbara',
            'Beate',
            'Beatrice',
            'Belinda',
            'Benedikta',
            'Bente',
            'Bettina',
            'Bianca',
            'Birgit',
            'Birte',
            'Brit',
            'Britta',
            'Carina',
            'Carla',
            'Carmen',
            'Carolin',
            'Caroline',
            'Celina',
            'Cecilia',
            'Celine',
            'Chloe',
            'Chiara',
            'Clara',
            'Clarissa',
            'Claudia',
            'Cornelia',
            'Cordula',
            'Corinna',
            'Charlotte',
            'Christiane',
            'Christina',
            'Christine',
            'Dagmar',
            'Daniela',
            'Daria',
            'Dea',
            'Deborah',
            'Denise',
            'Diana',
            'Dorina',
            'Dorothea',
            'Dorothee',
            'Doreen',
            'Doris',
            'Dunja',
            'Edda',
            'Edda Sophie',
            'Edith',
            'Eileen',
            'Elena',
            'Elina',
            'Elisa',
            'Elisabeth',
            'Elke',
            'Ella',
            'Elli',
            'Ellen',
            'Elsa',
            'Elvira',
            'Emely',
            'Emila',
            'Emilia',
            'Emilie',
            'Emily',
            'Emma',
            'Emma Wolke',
            'Enya',
            'Erna',
            'Elfriede',
            'Elif',
            'Erika',
            'Estelle',
            'Esther',
            'Eva',
            'Eva-Maria',
            'Farina',
            'Felicitas',
            'Fenja',
            'Finja',
            'Florentine',
            'Francesca',
            'Franka',
            'Franziska',
            'Frederike',
            'Freyja',
            'Freya',
            'Frida',
            'Frieda',
            'Fritzi',
            'Friederike',
            'Fatma',
            'Gabriele',
            'Gesine',
            'Gerda',
            'Gertrud',
            'Giulia',
            'Gisela',
            'Greta',
            'Gudrun',
            'Hanna',
            'Hannah',
            'Hariet',
            'Heidi',
            'Heike',
            'Helena',
            'Helene',
            'Helga',
            'Hedwig',
            'Henriette',
            'Henrike',
            'Hermine',
            'Hannelore',
            'Heidemarie',
            'Hildegard',
            'Ilona',
            'Imke',
            'Ida',
            'Inge',
            'Ingeborg',
            'Irmgard',
            'Ina',
            'Ines',
            'Inga',
            'Ingrid',
            'Ira',
            'Irene',
            'Irina',
            'Iris',
            'Isabel',
            'Isabella',
            'Isabell',
            'Ivana',
            'Ivonne',
            'Izabela',
            'Jacky',
            'Jacqueline',
            'Jana',
            'Janet',
            'Janina',
            'Janine',
            'Janna',
            'Jasmin',
            'Jasmina',
            'Jenny-Sophie',
            'Jessica',
            'Jette',
            'Joana',
            'Joanna',
            'Johanna',
            'Jolanda',
            'Josephine',
            'Judith',
            'Julia',
            'Juliana',
            'Juliane',
            'Jule',
            'Justine',
            'Jutta',
            'Kathalie',
            'Katharina',
            'Kathrin',
            'Katja',
            'Katrin',
            'Kerstin',
            'Karin',
            'Kim',
            'Kimberly',
            'Kira',
            'Kirsten',
            'Klara',
            'Kristina',
            'Kristin',
            'Kristine',
            'Larissa',
            'Lara',
            'Lara Emilia',
            'Lara-Sophie',
            'Laura',
            'Laura-Sophie',
            'Lea',
            'Leandra',
            'Leila',
            'Lejla',
            'Lena',
            'Lena-Sophie',
            'Leni',
            'Leonie',
            'Leonie-Sophie',
            'Leyla',
            'Lia',
            'Lia-Marie',
            'Lilja',
            'Lilian',
            'Lilli',
            'Lilly',
            'Lina',
            'Lina Marie',
            'Lina-Marie',
            'Linda',
            'Lindita',
            'Lisa',
            'Livia',
            'Lorena',
            'Louisa',
            'Lieselotte',
            'Lotte',
            'Lotta',
            'Lucia',
            'Lucie',
            'Luisa',
            'Luise',
            'Luna',
            'Luna-Marie',
            'Luzie',
            'Madeleine',
            'Maeva',
            'Mailin',
            'Maika',
            'Maja',
            'Malin',
            'Manuela',
            'Mara',
            'Mariana',
            'Marie',
            'Marie-Luise',
            'Marien',
            'Maria',
            'Marianne',
            'Magdalena',
            'Margarete',
            'Margit',
            'Marlies',
            'Meryem',
            'Marika',
            'Marilen',
            'Marina',
            'Marion',
            'Marlene',
            'Marta',
            'Martha',
            'Martina',
            'Mathilda',
            'Mathilde',
            'Mazline',
            'Mechthild',
            'Melanie',
            'Melina',
            'Melissa',
            'Merle',
            'Mette',
            'Michelle',
            'Mia',
            'Mia-Sophie',
            'Michaela',
            'Mila',
            'Mila Sophie',
            'Mila Sophia',
            'Mina',
            'Minna',
            'Mirka',
            'Miriam',
            'Miriam Sophie',
            'Monika',
            'Mona',
            'Myra',
            'Nadja',
            'Nadine',
            'Nane Leokatia',
            'Natalia',
            'Natalie',
            'Nathalie',
            'Nele',
            'Nele-Marie',
            'Nicole',
            'Nia',
            'Nina',
            'Nina-Marie',
            'Noemi',
            'Olga',
            'Paula',
            'Paulina',
            'Pauline',
            'Patricia',
            'Petra',
            'Philippa',
            'Pia',
            'Ramona',
            'Rebecca',
            'Regina',
            'Renate',
            'Rita',
            'Romy',
            'Rosa',
            'Rosalie',
            'Ronja',
            'Rosemarie',
            'Ruth',
            'Sabina',
            'Sabine',
            'Sabrina',
            'Sandra',
            'Sara',
            'Sarah',
            'Saskia',
            'Selina',
            'Selma',
            'Sieglinde',
            'Sigrid',
            'Silke',
            'Silvia',
            'Simone',
            'Sina',
            'Sonja',
            'Sophia',
            'Sophie',
            'Stefanie',
            'Stella',
            'Susanne',
            'Svea',
            'Svenja',
            'Sylvia',
            'Tabea',
            'Taleesa',
            'Tamara',
            'Tanja',
            'Tatjana',
            'Theresa',
            'Therese',
            'Tina',
            'Tina-Louise',
            'Tina-Marie',
            'Tina-Sophie',
            'Ulrike',
            'Uta',
            'Ute',
            'Ursula',
            'Valentina',
            'Valerie',
            'Vanessa',
            'Vera',
            'Verena',
            'Veronika',
            'Victoria',
            'Viktoria',
            'Viola',
            'Vivian',
            'Vivien',
            'Waltraud',
            'Wiebke',
            'Yasmin',
            'Yvonne',
            'Zara',
            'Zoe',
            'Zoey',
            'Zoé',
            'Zora',
            'Zeynep',
            'Ayse',
            'Agnes',
            'Anna',
            'Stephanie',
            'Mailin July',
            'Anda',
            'Franzi',
            'Merit',
            'Ellie',
            'Julie'
        ];

        sort($names, SORT_LOCALE_STRING);

        $list = [];
        $id = 1;
        foreach ($names as $firstname) {
            $list[] = new EA_FemaleFirstname($id++, $firstname);
        }

        return $list;
    }

    /**
     * Get the string representation of the entity.
     */
    public function __toString()
    {
        return $this->getFirstname();
    }

}